version: '3.8'

services:
  service:
    image: springboot3withfirebaseauth_back_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot3withfirebaseauth_back_container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "8000:8000"
    tty: true
    networks:
      - app_network
networks:
  app_network:
    driver: bridge