version: '3.8'

services:
  service:
    image: springboot3withfirebaseauth_back_image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot3withfirebaseauth_back_container
    env_file:
      - .env
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    restart: always
    ports:
      - "8000:8000"
    tty: true
    networks:
      - app_network
networks:
  app_network:
    driver: bridge